jobs:
 - name: aarch64_u16javall-testing
   type: runSh
   steps:
     - TASK:
         runtime:
           options:
             imageName: "drydock/aarch64_u16javall"
             imageTag: master
         script:
           - /usr/lib/jvm/java-8-oracle/bin/java -version
           - /usr/lib/jvm/java-7-openjdk-arm64/jre/bin/java -version
           - /usr/lib/jvm/java-8-openjdk-arm64/jre/bin/java -version
           - mvn --version
           - gradle --version 
           - ant -version
